### PR TITLE
Demo agent

### PR DESCRIPTION
**Pull request by MatthijsJWH**
Covers user stories 1 & 2 from sprint 6

### CODE REVIEW

**Comment by MatthijsJWH** [comment]
Can somebody run the agent to check if the merge has been completed succesfully, I unfortunately can't run GOAL-agents yet.

**Comment by MHMCD** [comment]
The GOAL-agent still works and I approve of the changes in the agent.

**Comment by lisv** [comment]
Yes, the agent can be merged!

**Comment by shdshdw** [comment]
I approve that the demo agent ronald branch has changes that can be merged to the demo agent branch.

**Pull request merged**
