### PR TITLE
Deliverables week 9

### PR DESCRIPTION
**Pull request by JoshCode**

### CODE REVIEW

**Comment by shdshdw** [comment]
Approved. The deliverables can be merged.

**Comment by MatthijsJWH** [comment]
There are 2 problems numbered 3 in the retrospective, this should be changed before merging.
If that is changed I approve

**Comment by lisv** [comment]
I worked on the architecture design so I approve that. Also, I just looked through the retrospective and it also looks fine.

**Comment by JoshCode** [comment]
@MatthijsJWH Solved

**Comment by MHMCD** [comment]
I approve both files as the only problem was solved and we made them together.

**Comment by JoshCode** [comment]
Merging, accidentally forgot [ci skip] for that last commit. PDF files shouldn't cause the build to fail ;)

**Pull request merged**
